package io.github.therealmone.tdf4j.generator;

import io.github.therealmone.tdf4j.commons.Module;
import io.github.therealmone.tdf4j.parser.Parser;
import io.github.therealmone.tdf4j.parser.config.AbstractParserModule;
import org.joor.Reflect;
import org.stringtemplate.v4.ST;

public class ParserGenerator implements Generator<Parser> {

    @Override
    public Parser generate(Module module) {
        if(!(module instanceof AbstractParserModule)) {
            throw new RuntimeException("Parser generates only from AbstractParserModule");
        }

        final AbstractParserModule parserModule = (AbstractParserModule) module;
        return process(parserModule);
    }

    private Parser process(final AbstractParserModule module) {
        final ST test = Templates.TEST.template();
        final String generatedClassName = "AutoGeneratedParserFrom_" + module.getClass().getName().replaceFirst(module.getClass().getPackage().getName() + ".", "");
        test.add("package", module.getClass().getPackage().getName());
        test.add("className", generatedClassName);
        System.out.println(test.render());
        return Reflect.compile(module.getClass().getPackage().getName() + "." + generatedClassName,
                test.render()
                ).create().get();
    }
}
