coverage:
  precision: 2
  round: nearest
  range: "40...70"
  ignore:
    - "core/src/main/java/org/tdf4j/core/model" #model
    - "tdf-parser/src/main/java/org/tdf4j/tdfparser/impl/TdfParserImpl.java" #tdf parser
